//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETCoffee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoffeeShopEntities : DbContext
    {
        public CoffeeShopEntities()
            : base("name=CoffeeShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategories> tblCategories { get; set; }
        public virtual DbSet<tblInvoice> tblInvoice { get; set; }
        public virtual DbSet<tblOrder> tblOrder { get; set; }
        public virtual DbSet<tblProducts> tblProducts { get; set; }
        public virtual DbSet<tblSit> tblSit { get; set; }
        public virtual DbSet<tblTable> tblTable { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<getallorders> getallorders { get; set; }
        public virtual DbSet<getallorderusers> getallorderusers { get; set; }
        public virtual DbSet<getAllTableSits> getAllTableSits { get; set; }
        public virtual DbSet<user_invoices> user_invoices { get; set; }
        public virtual DbSet<vw_getallproducts> vw_getallproducts { get; set; }
    }
}
