//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSit
    {
        public int sitId { get; set; }
        public byte available { get; set; }
        public int tableId { get; set; }
    
        public virtual tblTable tblTable { get; set; }
    }
}
